version: "3.6"
services:
  express-app-service:
    container_name: express-app-container-foo
    image: express-app:1.0.0
    restart: always
    build: ./
    ports:
      - "82:3000"
    networks:
      - express-mongo-net
    volumes:
      - type: bind
        source: ./
        target: /app
    depends_on:
      - mongo-db-service
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  mongo-db-service:
    container_name: mongo-db-container-foo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    networks:
      - express-mongo-net
    volumes:
      - db-volume:/var/lib/data
volumes:
  data-volume:
  db-volume:
networks:
  express-mongo-net: