version: "3"
services:
  myapp:
    container_name: foo-express-app
    image: express-app:1.0.0
    restart: always
    build: ./
    ports:
      - "80:3000"
    depends_on:
      - mymongo
  mymongo:
    container_name: foo-mongo-db
    image: mongo:latest
    ports:
      - "27017:27017"