version: "3"
services:
  myapp:
    container_name: express-mongo-app
    image: my-express-app:1.0
    restart: always
    build: ./
    ports:
      - "80:3000"
    volumes:
      - .:/app
    depends_on:
      - mymongo
  mymongo:
    container_name: mymongo-db
    image: mongo
    ports:
      - "27017:27017"